name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  ci:
    name: 'CI'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Maven test
        working-directory: .ci
        run: |
          docker compose pull --quiet

          mkdir -p ~/.m2/repository
          docker-compose run \
            --user="$(id -u):$(id -g)" \
            -v "$HOME/.m2/repository:/.m2/repository" \
            -e MAVEN_OPTS='-Dmaven.repo.local=/.m2/repository' \
            --rm \
            gnc4j-ci
