name: Perform release

on:
  workflow_dispatch:

jobs:
  deploy-maven-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Deploy Maven artifact
        run: |
          ./mvnw -Prelease -DskipTests deploy