name: Prepare release

on:
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
  prepare-release:
    name: 'Prepare release'
    needs:
      - ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Set release version
        id: set-release-version
        run: |
          ./mvnw -ntp org.codehaus.mojo:versions-maven-plugin:2.11.0:set -DgenerateBackupPoms=false -DprocessAllModules=true -DremoveSnapshot=true
          version="$(./mvnw -ntp help:evaluate -Dexpression=project.version -q -DforceStdout)"
          echo ::set-output name=version::"${version}"
      - name: Push release commit and tag
        uses: EndBug/add-and-commit@v9
        with:
          message: "Release version ${{ steps.set-release-version.outputs.version }}"
          tag: "${{ steps.set-release-version.outputs.version }}"