name: Prepare development

on:
  workflow_dispatch:
    inputs:
      next-development-version:
        required: true
        type: string
        description: The next version on which to begin development

jobs:
  prepare-development:
    name: 'Prepare development'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Set next development version
        run: |
          ./mvnw -ntp org.codehaus.mojo:versions-maven-plugin:2.11.0:set -DgenerateBackupPoms=false -DprocessAllModules=true -DnewVersion='${{ github.event.inputs.next-development-version }}'
          version="$(./mvnw -ntp help:evaluate -Dexpression=project.version -q -DforceStdout)"
          echo ::set-output name=version::"${version}"
      - name: Push next development commit and tag
        uses: EndBug/add-and-commit@v9
        with:
          message: "Next development version ${{ steps.set-next-development-version.outputs.version }}"